name: Dynamic README injection
permissions:
  contents: write
on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"
jobs:
  get-quote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: go.mod

      - name: Integrate
        run: go run ./cmd/quote-update

      - name: Add To Repo
        run: |
          git add .
          git config user.name QuoteInjector
          git config user.email QuoteInjector@github.com
          git commit -m "[Automated] push new quote"

      - name: Push
        uses: ad-m/github-push-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref_name }}
